### ISSUE TITLE
not triggering the initial sync

### ISSUE THREAD

**Issue by geraldodev** [multunus/dashboard-clj#4]
Hi,

I'm using sente 1.10.0, and It was not triggering the initial sync until I've changed the mechanism to detect first-open? on connect-to-data-sources.

```
(when (= id :chsk/state)
          (let [[ev-id [old-map {:as new-map :keys [first-open?]}]] event]
            (when first-open?
              (send-fn [:dashboard-clj.core/sync]))))
```

regards,

geraldodev

**Comment by tacticiankerala** [comment]
I think this is due to the [breaking change in sente v1.9.0 onwards](https://github.com/ptaoussanis/sente/blob/master/CHANGELOG.md#v190---2016-jul-6).

> BREAKING: Client-side event changed: [:chsk/state <new-state-map>] -> [:chsk/state [<old-state-map> <new-state-map>]]

dashboard-clj is using sente v1.8.1. I think we can update it to latest sente version (v1.10.0)

@geraldodev , will you be able to submit a pull request?

**Comment by geraldodev** [comment]
Sorry for not submiting a pull request. I'm very glad and interested in
dashboard-clj, but I don't consider myself proficient on its inner workings
yet.

Today was my fist day with client side.

regards,

geraldodev

2016-08-17 17:54 GMT-03:00 Sreenath Nannat notifications@github.com:

**Comment by jerryjohnjacob** [comment]
@geraldodev We're also a little new to the scene ourselves 😃 . Your approach looks good - doing great for a new guy :). I think it'd be great if you can submit a pull request with the updates.
